#!/bin/bash

./htk/HVite -C htk/config1 -H htk/hmm12/macros -H htk/hmm12/hmmdefs -S htk/test-wav.scp -l '*' -i htk/recout-wav.mlf -w htk/wdnet -p 0.0 -s 5.0 htk/dict htk/triphones1
#./HResults -I testref.mlf triphones1 recout-wav.mlf
